name: Formatting Check

on: pull_request

jobs:

  main:
    name: Check code formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Opentofu
        uses: opentofu/setup-opentofu@v1

      - name: Tofu Format
        id: fmt
        run: tofu fmt -check -recursive -diff
